<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net472</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <LangVersion>10</LangVersion>
    <AssemblyName>JianpuEditor</AssemblyName>
    <RootNamespace>JianpuEditor</RootNamespace>
    <ApplicationIcon />
    <Nullable>disable</Nullable>
    <PackageLicenseExpression>Apache-2.0</PackageLicenseExpression>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
    <PackageReference Include="PDFsharp" Version="6.2.0" />
  </ItemGroup>
</Project>